import { Course, CourseAvatar, CourseGridContent } from "./interface";

const demoAvatars: CourseAvatar[] = [
  { src: "https://i.pravatar.cc/100?img=1", alt: "Student 1" },
  { src: "https://i.pravatar.cc/100?img=5", alt: "Student 2" },
  { src: "https://i.pravatar.cc/100?img=8", alt: "Student 3" },
];

export const courses: Course[] = [
  {
    id: "figma-basics",
    title: "Learn Figma from Basic",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "25+",
  },
  {
    id: "digital-asset",
    title: "Build Digital Asset",
    image: "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "20+",
  },
  {
    id: "big-data",
    title: "the Power of Big Data",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "26+",
  },
  {
    id: "productivity",
    title: "Balancing Productivity and…",
    image: "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "26+",
  },
  {
    id: "money-management",
    title: "Mastering Money Manageme…",
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "26+",
  },
  {
    id: "startup-success",
    title: "From Idea to Startup Succe…",
    image: "https://images.unsplash.com/photo-1521737604893-d14cc237f11d?w=600",
    lessons: 17,
    durationLabel: "2 hours 16 mins",
    comments: 59,
    rating: 4.5,
    instructor: "purapearl studio",
    level: "Beginner",
    price: 25,
    originalPrice: 35,
    avatars: demoAvatars,
    studentCountLabel: "26+",
  },
];

export async function getCourseGrid(): Promise<CourseGridContent> {
  await new Promise((resolve) => setTimeout(resolve, 2000));

  return {
    title: "Discover Your Passion, Build Your Skills",
    description:
      "At Bytespace Courses, we bring you closer to life-changing knowledge. Explore a variety of courses across different fields, from technology to the arts, and make a difference in your career and life.",
    categories,
    courses,
  };
}

export const categories: string[] = [
  "Featured",
  "Music",
  "Drawing & Painting",
  "Marketing",
  "Animation",
  "Social Media",
  "UI/UX Design",
  "Creative Marketing",
  "Digital Illustration",
  "Film & Video",
  "Crafts",
  "Freelance & Entrepreneurship",
  "Graphic Design",
  "Photography",
  "Productivity",
  "Web Development",
  "Data Science",
  "Cooking",
];
